# Generated by Django 2.2 on 2019-04-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElecModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(default='', max_length=10, verbose_name='voterid')),
                ('name', models.CharField(default='', max_length=50, verbose_name='name')),
                ('Address', models.TextField(default='', verbose_name='address')),
                ('number', models.BigIntegerField(default='', verbose_name='number')),
                ('gender', models.BooleanField(verbose_name='gender')),
            ],
        ),
    ]
